project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "Causal Inference"
  navbar:
    tools:
      - icon: github
        href: "https://github.com/stefanocoretta/causal-inference"
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      - brite.scss
      - brand
    css: styles.css
    toc: true

callout-icon: false

