project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "Causal Inference"
  navbar:
    tools:
      - icon: github
        href: "https://github.com/stefanocoretta/causal-inference"
    left:
      - href: index.qmd
        text: Home
      - href: slides/index.qmd
        text: Slides

format:
  html:
    theme:
      - brite.scss
      - brand
    css: styles.css
    toc: true

callout-icon: false

editor: 
  markdown: 
    canonical: true
    wrap: sentence

execute:
  cache: true
  freeze: auto