---
title: "Causal Inference: correlation *is* causation"
bibliography: references.bib
---

This is the website of the [STeW](https://uoelel.github.io/stew.html) workshop *Causal inference: correlation is causation*.

|  |  |
|----------------|--------------------------------------------------------|
| **Level** | 🟠 Intermediate |
| **Description** | In this workshop, you will learn the basics of causal inference and how regression models can help estimate causal effects. Causal inference is based on the theory of Directed Acyclic Graphs (DAGs), which will be introduced with examples from linguistics. |
| **Prerequisites** | Familiarity with regression models is necessary to understand the application of DAG theory to data analysis, but anyone with at least some prior statistical background is welcome to join. |
| **Recording** |  |

## Further readings

- @mcelreath2020: Chapters 5-6.

  - There are also video lectures, available here: <https://github.com/rmcelreath/stat_rethinking_2026>.

- @rohrer2018, @rohrer2024.

- @pearl2014 and Pearl's *The Book of Why*.
  Judea Pearl is the founder of causal inference based on *do*-calculus, which is the one adopted in @mcelreath2020 and in this workshop.

- @greenland2011, @pearce2016.
