---
title: "Causal Inference for linguistics"
author: "Stefano Coretta"
format: revealjs
knitr:
  opts_chunk:
    dev: png
    dev.args:
      bg: transparent
---


## {background-image="../img/courtney-cook-66IZaW9LIpI-unsplash.jpg"}

[**Correlation is NOT causation**]{style="font-size: 60px"}

[Photo by <a href="https://unsplash.com/@courtneymcook?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Courtney Cook</a> on <a href="https://unsplash.com/photos/four-round-white-and-brown-ornaments-66IZaW9LIpI?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>]{style="font-size: 8px;"}

## Clothing and ice cream

<br><br>

::: {style="text-align: center; font-size: 50px;"}
🎽 shorter clothing ↔️ more ice cream 🍨
::::

## Counfound

```{r}
#| label: setup
#| include: false

library(tidyverse)
library(ggdag)
```

```{r}
temp <- dagify(
  Clothing ~ Temperature,
  Icecream ~ Temperature,
  coords = list(
    x = c(Clothing = 1, Icecream = 2, Temperature = 1.5),
    y = c(Clothing = 1, Icecream = 1, Temperature = 2)
  )
)

ggplot(temp, aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_dag_edges() +
  geom_dag_label() +
  theme_dag(
    base_size = 20,
    panel.background = element_rect(fill = "transparent", colour = NA),
    plot.background  = element_rect(fill = "transparent", colour = NA)
  )
```

